pipeline {
    agent any
    stages {
        stage('Navigate and Run') {
            steps {
                dir('PythonProject') {
                    bat 'python jenks.py'
                }
            }
        }
    }
}
